<a href="https://colab.research.google.com/github/gitmystuff/DTSC5502/blob/main/Module_06-Feature_Engineering/PrepPy_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PrepPy Example

https://github.com/gitmystuff/preppy

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/refs/heads/main/Advertising%20Mess.csv')
print(df.shape)
print(df.info())
df.head()

(221, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   radio               200 non-null    float64
 1   social              202 non-null    float64
 2   fake_date_of_birth  221 non-null    object
 3   station             221 non-null    float64
 4   xyz                 221 non-null    object
 5   newspaper           200 non-null    float64
 6   then                221 non-null    float64
 7   sales               200 non-null    float64
 8   effort              221 non-null    float64
 9   fake_surname        221 non-null    object
 10  politics            199 non-null    float64
 11  fake_name           221 non-null    object
 12  xy                  212 non-null    object
 13  science             208 non-null    float64
 14  break               221 non-null    float64
 15  Unnamed: 0          200 non-null    float64
 16  worker              221 non-null    float64
 17  low                 221 non-null    float64
 18  fake_misc           205 non-null    object
 19  value               221 non-null    float64
 20  fake_zipcode        221 non-null    int64
 21  off                 221 non-null    int64
 22  TV                  200 non-null    float64
dtypes: float64(15), int64(2), object(6)
memory usage: 39.8+ KB
None

,radio,social,fake_date_of_birth,station,xyz,newspaper,then,sales,effort,fake_surname,...,science,break,Unnamed: 0,worker,low,fake_misc,value,fake_zipcode,off,TV
0,1.5,1.061126,2006-10-07,-1.969540,catch,33.0,0.03,7.3,0.07,Santos,...,1.061126,-1.37,92.0,1.368499,-1.37,'case',0.088866,72546,19799,28.6
1,19.2,0.011220,1922-08-22,-1.151342,child,16.6,0.03,13.2,0.07,Barnes,...,0.011220,-0.88,58.0,0.881218,-0.88,'child',0.769275,82586,26613,136.2
2,17.4,-0.674410,2015-10-10,-2.068512,identify,38.6,0.03,11.9,0.07,Lopez,...,-0.674410,1.50,32.0,1.495952,1.50,'state',0.499968,92448,24092,112.9
3,2.9,-2.227874,2003-11-18,-1.857568,bar,43.0,0.03,12.7,0.07,Moore,...,-2.227874,1.13,132.0,1.127053,1.13,'state',1.738265,35976,12429,265.2
4,7.6,-1.039743,2007-04-16,-0.561947,that,7.2,0.03,9.7,0.07,Arroyo,...,-1.039743,0.29,14.0,0.292174,0.29,'arm',1.019021,56387,25680,97.5

## PrepPy

https://github.com/gitmystuff/preppy.git

<pre>
! git clone https://github.com/gitmystuff/preppy.git

from preppy.version import __version__
print(__version__)
</pre>

PrepPy Functions
* identify_consts
* identify_quasi_consts
* check_row_duplicates
* check_col_duplicates
* handle_missing_values
* handle_standard_scaler
* handle_minmax_scaler
* handle_outliers
* do_OHE

In [2]:
# !git clone https://github.com/gitmystuff/preppy.git

Cloning into 'preppy'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 66 (delta 30), reused 32 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (66/66), 23.40 KiB | 3.90 MiB/s, done.
Resolving deltas: 100% (30/30), done.

In [3]:
from preppy.version import __version__

print(__version__)

PrepPy Version: 0.1.0

In [4]:
# drop Unnamed: 0
df.drop('Unnamed: 0', axis=1, inplace=True)
print(df.shape)

(221, 22)

In [5]:
# identify_consts
import preppy.utils as utils

consts = utils.functions.identify_consts(df)
consts

['then', 'effort']

In [6]:
df.drop(consts, axis=1, inplace=True)
print(df.shape)

(221, 20)

In [7]:
quasi_consts = utils.functions.identify_quasi_consts(df)
quasi_consts

[]

In [8]:
utils.functions.check_row_duplicates(df)

0

In [9]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html
df[df.duplicated(subset=['fake_zipcode'])].count()

radio                 17
social                20
fake_date_of_birth    21
station               21
xyz                   21
newspaper             17
sales                 17
fake_surname          21
politics              20
fake_name             21
xy                    20
science               19
break                 21
worker                21
low                   21
fake_misc             20
value                 21
fake_zipcode          21
off                   21
TV                    17
dtype: int64

In [10]:
print(df.shape)
df.drop_duplicates(subset=['fake_zipcode'], inplace=True)
print(df.shape)

(221, 20)
(200, 20)

In [11]:
duplicate_features = utils.functions.check_col_duplicates(df)
print(duplicate_features)

['low']

In [12]:
df.drop(duplicate_features, axis=1, inplace=True)
print(df.shape)

(200, 19)

In [13]:
df.describe()

,radio,social,station,newspaper,sales,politics,science,break,worker,value,fake_zipcode,off,TV
count,183.000000,182.000000,200.000000,183.000000,183.000000,179.000000,189.000000,200.00000,200.000000,200.000000,200.000000,200.000000,183.000000
mean,23.642623,-0.793991,-1.185212,30.650273,14.167213,0.007777,-0.800852,-0.00980,0.815211,1.148092,49607.430000,19679.690000,149.600000
std,14.811354,1.174434,0.837920,21.772439,5.230029,0.961068,1.174260,0.99379,0.565957,0.857799,30656.933345,5941.989166,85.531488
min,0.000000,-5.137004,-3.663322,0.300000,1.600000,-1.997366,-5.137004,-2.24000,-0.018041,0.011959,1447.000000,10125.000000,0.700000
25%,10.350000,-1.629548,-1.842049,12.700000,10.450000,-0.703391,-1.557685,-0.72000,0.343247,0.496913,19848.000000,13645.000000,75.200000
50%,23.600000,-0.758927,-0.976221,25.600000,13.200000,0.009735,-0.766612,0.00500,0.711485,0.965053,50013.500000,19771.500000,163.500000
75%,36.850000,0.009507,-0.506238,45.550000,17.500000,0.644415,0.011220,0.64000,1.250078,1.679383,76606.250000,25019.000000,220.050000
max,49.600000,1.856937,0.007158,114.000000,27.000000,2.348718,1.816581,2.35000,2.348718,4.484226,99886.000000,29967.000000,293.600000

In [14]:
df = utils.functions.handle_standard_scaler(df)
df.describe()

,radio,social,station,newspaper,sales,politics,science,break,worker,value,fake_zipcode,off,TV
count,183.000000,182.000000,200.000000,183.000000,183.000000,179.000000,189.000000,200.00000,200.000000,200.000000,2.000000e+02,200.000000,183.000000
mean,23.642623,-0.793991,-1.185212,30.650273,14.167213,0.007777,-0.800852,-0.00980,0.815211,1.148092,-1.332268e-17,19679.690000,149.600000
std,14.811354,1.174434,0.837920,21.772439,5.230029,0.961068,1.174260,0.99379,0.565957,0.857799,1.002509e+00,5941.989166,85.531488
min,0.000000,-5.137004,-3.663322,0.300000,1.600000,-1.997366,-5.137004,-2.24000,-0.018041,0.011959,-1.574890e+00,10125.000000,0.700000
25%,10.350000,-1.629548,-1.842049,12.700000,10.450000,-0.703391,-1.557685,-0.72000,0.343247,0.496913,-9.731602e-01,13645.000000,75.200000
50%,23.600000,-0.758927,-0.976221,25.600000,13.200000,0.009735,-0.766612,0.00500,0.711485,0.965053,1.327886e-02,19771.500000,163.500000
75%,36.850000,0.009507,-0.506238,45.550000,17.500000,0.644415,0.011220,0.64000,1.250078,1.679383,8.828858e-01,25019.000000,220.050000
max,49.600000,1.856937,0.007158,114.000000,27.000000,2.348718,1.816581,2.35000,2.348718,4.484226,1.644155e+00,29967.000000,293.600000

In [15]:
df = utils.functions.handle_minmax_scaler(df)
df.describe()

,radio,social,station,newspaper,sales,politics,science,break,worker,value,fake_zipcode,off,TV
count,183.000000,182.000000,200.000000,183.000000,183.000000,179.000000,189.000000,200.00000,200.000000,200.000000,2.000000e+02,200.000000,183.000000
mean,23.642623,-0.793991,-1.185212,30.650273,14.167213,0.007777,-0.800852,-0.00980,0.815211,1.148092,-1.332268e-17,0.481539,149.600000
std,14.811354,1.174434,0.837920,21.772439,5.230029,0.961068,1.174260,0.99379,0.565957,0.857799,1.002509e+00,0.299465,85.531488
min,0.000000,-5.137004,-3.663322,0.300000,1.600000,-1.997366,-5.137004,-2.24000,-0.018041,0.011959,-1.574890e+00,0.000000,0.700000
25%,10.350000,-1.629548,-1.842049,12.700000,10.450000,-0.703391,-1.557685,-0.72000,0.343247,0.496913,-9.731602e-01,0.177401,75.200000
50%,23.600000,-0.758927,-0.976221,25.600000,13.200000,0.009735,-0.766612,0.00500,0.711485,0.965053,1.327886e-02,0.486166,163.500000
75%,36.850000,0.009507,-0.506238,45.550000,17.500000,0.644415,0.011220,0.64000,1.250078,1.679383,8.828858e-01,0.750630,220.050000
max,49.600000,1.856937,0.007158,114.000000,27.000000,2.348718,1.816581,2.35000,2.348718,4.484226,1.644155e+00,1.000000,293.600000

In [16]:
df.isnull().sum()

radio                 17
social                18
fake_date_of_birth     0
station                0
xyz                    0
newspaper             17
sales                 17
fake_surname           0
politics              21
fake_name              0
xy                     8
science               11
break                  0
worker                 0
fake_misc             15
value                  0
fake_zipcode           0
off                    0
TV                    17
dtype: int64

In [17]:
df = utils.functions.handle_missing_values(df)
df.isnull().sum()

radio                 0
social                0
fake_date_of_birth    0
station               0
xyz                   0
newspaper             0
sales                 0
fake_surname          0
politics              0
fake_name             0
xy                    0
science               0
break                 0
worker                0
fake_misc             0
value                 0
fake_zipcode          0
off                   0
TV                    0
dtype: int64

In [18]:
df = utils.functions.handle_outliers(df)

## One Hot Encoding

See Notebook

In [19]:
df = utils.functions.do_OHE(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 219
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   radio               200 non-null    float64
 1   social              200 non-null    float64
 2   fake_date_of_birth  200 non-null    float64
 3   station             200 non-null    float64
 4   xyz                 200 non-null    float64
 5   newspaper           200 non-null    float64
 6   sales               200 non-null    float64
 7   fake_surname        200 non-null    float64
 8   politics            200 non-null    float64
 9   fake_name           200 non-null    float64
 10  xy                  200 non-null    float64
 11  science             200 non-null    float64
 12  break               200 non-null    float64
 13  worker              200 non-null    float64
 14  fake_misc           200 non-null    float64
 15  value               200 non-null    float64
 16  fake_zipcode        200 non-null    float64
 17  off                 200 non-null    float64
 18  TV                  200 non-null    float64
dtypes: float64(19)
memory usage: 39.4 KB

In [20]:
df.head()

,radio,social,fake_date_of_birth,station,xyz,newspaper,sales,fake_surname,politics,fake_name,xy,science,break,worker,fake_misc,value,fake_zipcode,off,TV
0,1.5,1.061126,0.005,-1.969540,0.005,0.247285,7.3,0.010,-1.368499,0.005,0.010,1.061126,-1.37,1.368499,0.025,0.088866,0.750112,0.487552,28.6
1,19.2,0.011220,0.005,-1.151342,0.005,-0.300752,13.2,0.005,-0.881218,0.020,0.010,0.011220,-0.88,0.881218,0.010,0.769275,1.078429,0.830965,136.2
2,17.4,-0.674410,0.005,-2.068512,0.005,0.434419,11.9,0.010,1.495952,0.005,0.005,-0.674410,1.50,1.495952,0.115,0.499968,1.400925,0.703911,112.9
3,2.9,-2.227874,0.005,-1.857568,0.005,0.581454,12.7,0.005,1.127053,0.020,0.005,-2.227874,1.13,1.127053,0.115,1.738265,-0.445760,0.116117,265.2
4,7.6,-1.039743,0.005,-0.561947,0.005,-0.614871,9.7,0.005,0.292174,0.005,0.005,-1.039743,0.29,0.292174,0.020,1.019021,0.221698,0.783943,97.5